name: 'dogspipeline'
version: '1.0.0'
config-version: 2

profile: 'dogspipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  dogspipeline:
    intermediate:
      +materialized: view
      snowflake_warehouse: COMPUTE_WH
    +depends_on:
      - model: dim_order
      - model: dim_dog
      - model: dim_veterinarian
      - model: dim_appointment
      - model: dim_product
