dogspipeline:
  outputs:
    dev:
      type: snowflake 
      account: fmfghgx-ll43764

      user: TEST_DOGS
      password: "Dogstest1"

      role: ACCOUNTADMIN
      database: DOGPIPELINE
      warehouse: COMPUTE_WH
      schema: DOGS
      threads: 1
  target: dev
